---
- hosts: localhost
  become: true
  gather_facts: true
  pre_tasks:
    - name: add additional repos
      apt_repository:
        repo: universe
        state: present

    - name: update all repos
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Update all packages to latest
      apt:
        name: "*"
        state: latest

  tasks:
    - name: Install packages
      include: tasks/packages.yml

    - name: Configure ZSH
      include: tasks/config_zsh.yml
      become_user: "{{ username }}"

    - name: Install nvm and node LTS
      include: tasks/config_zsh.yml
      become_user: "{{ username }}"
