---
  - name: Configure zsh
    shell: chsh -s $(which zsh)

  - name: download and install ohmyzsh
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  - name: download my zsh conf
    get_url:
      url: https://gist.githubusercontent.com/mishaal79/b56d1489c8246f6683f9fc1ac69e49ef/raw/944848c59a0af252d98f3726a5f22f4a2535b1fb/.zshrc
      dest: "/home/{{ username }}.zshrc.conf"
      mode: '0440'

  