---
- name: Install packages
  apt:
    name: { { item } }
    with_items: { { apt_packages } }

- name: Install Joplin
  shell: >
    wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash

- name: Install python modules
  pip:
    name: { { item } }
    with_items: { { python_modules } }
    args: --user
